NAME: InterGen
NUM_LAYERS: 8
NUM_HEADS: 8
DROPOUT: 0.1
INPUT_DIM: 262
LATENT_DIM: 1024
FF_SIZE: 2048
ACTIVATION: gelu
CHECKPOINT: checkpoints/intergen.ckpt

DIFFUSION_STEPS: 1000
BETA_SCHEDULER: cosine
SAMPLER: uniform

MOTION_REP: global
FINETUNE: False

TEXT_ENCODER: clip
T_BAR: 700

CONTROL: text
STRATEGY: ddim50
CFG_WEIGHT: 3.5

